version: '3'
services:
  postgres:
    image: postgres
    container_name: ecom_pg
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
